[project]
name = "mimic-me"
version = "0.1.0"
description = ""
authors = [
    {name = "zaki",email = "mog5808@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.11"

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["migrations"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
